
Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-v47rb[0m
{"level":"warn","ts":1583480942.7979722,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1583480942.7986166,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-g6rc8[0m
{"level":"warn","ts":1583480943.1972368,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1583480943.1983294,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-vicky-socs-test-python-jenkins-cfns6-xksck[0m
{"level":"warn","ts":1583480949.3616905,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1583480951.8779304,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/test-python-jenkins.git @ v0.0.1 in path /workspace/source"}

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:4d647c213e8ac907092bec0d35f65760755927c0
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2020/03/06 07:49:15 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
2020/03/06 07:49:17 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0004] Executing 3 build triggers                   
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] Checking for cached layer 685249416972.dkr.ecr.ap-south-1.amazonaws.com/todo/cache:20ed5631d983ab35ddcc4224cde40d34ba4dcc68c4ee26635bbf30d01c3c2af6... 
[36mINFO[0m[0004] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Using files from context: [/workspace/source] 
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] Skipping unpacking as no commands require it. 
[36mINFO[0m[0004] Taking snapshot of full filesystem...        
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Found cached layer, extracting to filesystem 
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source] 
[36mINFO[0m[0005] COPY . /usr/src/app                          
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] COPY requirements.txt .                      
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] ENV PORT 8080                                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] EXPOSE 8080                                  
[36mINFO[0m[0005] cmd: EXPOSE                                  
[36mINFO[0m[0005] Adding exposed port: 8080/tcp                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] ENTRYPOINT ["python"]                        
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] CMD ["app.py"]                               
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
2020/03/06 07:49:20 pushed blob: sha256:0d6f22221acb3cb39ba1a41c9d0700d901085c182788af9dea3b143c2158a213
2020/03/06 07:49:21 pushed blob: sha256:585af2da54a34f97a654e645b61bce9e40babda24e7615a97054da053f3d0057
2020/03/06 07:49:21 pushed blob: sha256:0e4a9f38336dffab066a4f69a71c8bb97faf4524149d06d2cf27891edf06754a
2020/03/06 07:49:21 pushed blob: sha256:f1c143820ddaeef2bd557cb9725b67437d4e087862f4760feb3529d529e7081c
2020/03/06 07:49:21 pushed blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/03/06 07:49:22 pushed blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/03/06 07:49:22 pushed blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/03/06 07:49:22 pushed blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/03/06 07:49:22 pushed blob: sha256:2faf2c6188442fb2d5d9154d35d2fd9e051bfd27bdc642549fb2201bb441120d
2020/03/06 07:49:23 pushed blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/03/06 07:49:23 pushed blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/03/06 07:49:24 pushed blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/03/06 07:49:24 pushed blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/03/06 07:49:29 pushed blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/03/06 07:49:29 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkins:0.0.1: digest: sha256:a36a6eb036650cd9f573bb0b43692690aa6c2f8049d65569ecadc0b8ca86744c size: 2385

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/test-python-jenkins to an unshallow repository
Generating change log from git ref d09dcb2dc9625fae3a8edb520e40e1bd58ee577f => a3e14a2d41c1d64a07abd3921eb3a0422c39cc4a
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 4d647c213e8ac907092bec0d35f65760755927c0 with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 4d647c213e8ac907092bec0d35f65760755927c0 with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 6caab88ee8a63211d731353a97234c1c0393fd78 with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 6caab88ee8a63211d731353a97234c1c0393fd78 with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
WARNING: Failed to enrich commit c361390204fb45606ff01fe7d42e09e83e58ccc7 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit c361390204fb45606ff01fe7d42e09e83e58ccc7 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit efb5c485280c97f2b55a97083d6e8c35d93166fb with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit efb5c485280c97f2b55a97083d6e8c35d93166fb with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit f9a43c0cc3499587782e9467bfa8b0e29f6d2c8e with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit f9a43c0cc3499587782e9467bfa8b0e29f6d2c8e with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 787ecca85430d6da2fa5e66d81abf08364d6ace1 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 787ecca85430d6da2fa5e66d81abf08364d6ace1 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit a830ca4edbe18eed29768f39e64cc5fea70a2a55 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit a830ca4edbe18eed29768f39e64cc5fea70a2a55 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 6e3b46f5f6dabf0465fa83df30619e3309d50009 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 6e3b46f5f6dabf0465fa83df30619e3309d50009 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit a0ad68067c67a4218f1530861af5fe17442bdea4 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit a0ad68067c67a4218f1530861af5fe17442bdea4 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit bee43b47db34e4df7bbf2a357578bb604d947394 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit bee43b47db34e4df7bbf2a357578bb604d947394 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 1502eef6c70a57b1b083a9c8ad68833303a5b046 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 1502eef6c70a57b1b083a9c8ad68833303a5b046 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 428ce7d88a9f4faa539c7f71d62175910358dcbb with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 428ce7d88a9f4faa539c7f71d62175910358dcbb with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 0b8001cd2816ec6512f02e098c050ed10112a7af with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 0b8001cd2816ec6512f02e098c050ed10112a7af with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 10441d129d7f2dd06cd1af6c0de757aa06654497 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 10441d129d7f2dd06cd1af6c0de757aa06654497 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 62aaf2353bb7e19620ee46e01c12b3e294bdf473 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit 62aaf2353bb7e19620ee46e01c12b3e294bdf473 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit d8c8bb634ca5b358a9501913545262bc8bcd8858 with issues: users.jenkins.io "x-0" already exists
WARNING: Failed to enrich commit d8c8bb634ca5b358a9501913545262bc8bcd8858 with issues: users.jenkins.io "x-0" already exists
WARNING: No release found for vicky-socs/test-python-jenkins and tag v0.0.1 so creating a new release
Updated the release information at https://github.com/vicky-socs/test-python-jenkins/releases/tag/v0.0.1
generated: /workspace/source/charts/test-python-jenkins/templates/release.yaml
Created Release test-python-jenkins-0-0-1 resource in namespace **
Updating PipelineActivity vicky-socs-test-python-jenkins-master-1 with version 0.0.1
Updated PipelineActivities vicky-socs-test-python-jenkins-master-1 with release notes URL: https://github.com/vicky-socs/test-python-jenkins/releases/tag/v0.0.1

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file test-python-jenkins-0.0.1.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mvicky-socs-test-python-jenkins-cfns6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Promoting app test-python-jenkins version 0.0.1 to namespace **-staging
WARNING: 
Created Pull Request: https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/5
Added label updatebot to Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/5
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/5
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/5
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/5
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/5
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/5
Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/5 is merged at sha 5175ed83234aafa1a85dbca1d7d04b9de39a275f
Pull Request merged but we are not waiting for the update pipeline to complete!
WARNING: Could not find the service URL in namespace **-staging for names test-python-jenkins, **-test-python-jenkins, **-staging-test-python-jenkins
